### ISSUE TITLE
Using a nil pointer of a type which implementers driver.Valuer panics when used as param

### ISSUE THREAD

**Issue by tomwassing** [go-pg/pg#1344]
I'm experiencing a panic when executing an SQL query. The panic is caused by a query parameter. The type of the query parameter is a pointer to a struct which implements `driver.Valuer`. The value of the pointer is `nil`. I was expecting the value to be `NULL`, when placed inside the statement.

**Example code:**
```
var p *pgtype.Point // implements driver.Valuer
p = nil
_, _ := c.e.ExecContext(ctx, "INSERT INTO points (point) VALUES (?)", p)
```

**Stacktrace:**
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1520767]

goroutine 19 [running]:
testing.tRunner.func1(0xc00036e200)
	/usr/local/Cellar/go/1.12.7/libexec/src/testing/testing.go:830 +0x392
panic(0x160a8a0, 0x1be5370)
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:522 +0x1b5
github.com/jackc/pgx/pgtype.(*Point).EncodeText(0x0, 0x0, 0xc000026ac0, 0x0, 0x20, 0x51fe00, 0x1520e00, 0x1056401, 0x0, 0x8)
	/Users/tom/go/pkg/mod/github.com/jackc/pgx@v3.5.0+incompatible/pgtype/point.go:94 +0x37
github.com/jackc/pgx/pgtype.EncodeValueText(0x17892e0, 0x0, 0xc000012000, 0x2356270, 0x1611c80, 0x157158b)
	/Users/tom/go/pkg/mod/github.com/jackc/pgx@v3.5.0+incompatible/pgtype/database_sql.go:34 +0x7c
github.com/jackc/pgx/pgtype.(*Point).Value(0x0, 0x166b038, 0xc0001fb620, 0x100ab06, 0x1c143f0)
	/Users/tom/go/pkg/mod/github.com/jackc/pgx@v3.5.0+incompatible/pgtype/point.go:141 +0x37
github.com/go-pg/pg/types.appendDriverValuer(0xc00039c000, 0x127, 0x1000, 0x2356270, 0x0, 0x1, 0x2356230, 0x125, 0xc0001fb6d0)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/types/append.go:205 +0x49
github.com/go-pg/pg/types.Append(0xc00039c000, 0x127, 0x1000, 0x166b000, 0x0, 0x1, 0xc00039c000, 0x125, 0x1000)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/types/append.go:51 +0x38b
github.com/go-pg/pg/orm.Formatter.appendParam(0x0, 0xc00039c000, 0x127, 0x1000, 0x166b000, 0x0, 0xc00039c000, 0x125, 0x1000)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/orm/format.go:301 +0x82
github.com/go-pg/pg/orm.Formatter.append(0x0, 0xc00039c000, 0x125, 0x1000, 0xc0001fb8f0, 0xc000091520, 0xd, 0xd, 0x16bb851, 0xc000090a90, ...)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/orm/format.go:280 +0x41f
github.com/go-pg/pg/orm.Formatter.Append(0x0, 0xc00039c000, 0x5, 0x1000, 0x16deaa2, 0xfb, 0xc000091520, 0xd, 0xd, 0x15d2660, ...)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/orm/format.go:182 +0x230
github.com/go-pg/pg.(*baseDB).FormatQuery(0xc00030c370, 0xc00039c000, 0x5, 0x1000, 0x16deaa2, 0xfb, 0xc000091520, 0xd, 0xd, 0xc000180280, ...)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/base.go:443 +0x98
github.com/go-pg/pg.appendQuery(0xc00039c000, 0x5, 0x1000, 0x1789020, 0xc00030c370, 0x15d2660, 0xc000308de0, 0xc000091520, 0xd, 0xd, ...)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/messages.go:428 +0x213
github.com/go-pg/pg.writeQueryMsg(0xc00008e6c0, 0x1789020, 0xc00030c370, 0x15d2660, 0xc000308de0, 0xc000091520, 0xd, 0xd, 0x181e6db, 0x1bf7960)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/messages.go:412 +0xdd
github.com/go-pg/pg.(*baseDB).simpleQuery.func1(0xc00008e6c0, 0x0, 0x0)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/base.go:470 +0x6d
github.com/go-pg/pg/internal/pool.(*Conn).WithWriter(0xc000360200, 0x0, 0xc0001fbbc8, 0xc0000100a8, 0xc0001fbc50)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/internal/pool/conn.go:102 +0x79
github.com/go-pg/pg.(*baseDB).simpleQuery(0xc00030c370, 0xc000360200, 0x15d2660, 0xc000308de0, 0xc000091520, 0xd, 0xd, 0xc000091520, 0xd, 0xd, ...)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/base.go:469 +0xdb
github.com/go-pg/pg.(*Tx).exec.func1(0xc000360200, 0x16e71e8, 0x0)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/tx.go:135 +0x126
github.com/go-pg/pg.(*baseDB).withConn(0xc00030c370, 0x1797e20, 0xc0000c2000, 0xc000085560, 0x0, 0x0)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/base.go:152 +0xcb
github.com/go-pg/pg.(*Tx).withConn(...)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/tx.go:87
github.com/go-pg/pg.(*Tx).exec(0xc000020c80, 0x1797e20, 0xc0000c2000, 0x15d2660, 0xc000308de0, 0xc000091520, 0xd, 0xd, 0x0, 0x18, ...)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/tx.go:133 +0x12a
github.com/go-pg/pg.(*Tx).ExecContext(...)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/tx.go:129
github.com/go-pg/pg.(*Tx).execOne(0xc000020c80, 0x1797e20, 0xc0000c2000, 0x15d2660, 0xc000308de0, 0xc000091520, 0xd, 0xd, 0xc00000fba0, 0xc0003740c8, ...)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/tx.go:152 +0x8e
github.com/go-pg/pg.(*Tx).ExecOneContext(0xc000020c80, 0x1797e20, 0xc0000c2000, 0x15d2660, 0xc000308de0, 0xc000091520, 0xd, 0xd, 0xc00018c860, 0x15d2660, ...)
	/Users/tom/go/pkg/mod/github.com/go-pg/pg@v8.0.5+incompatible/tx.go:148 +0x87
github.com/tomwassing/x/pkg/storage/postgres.(*postgresClient).CreateX(0xc00018c820, 0x1797e20, 0xc0000c2000, 0xc000374000, 0x1, 0x1, 0x1)
	/Users/tom/git/xxx/pkg/storage/postgres/xxx.go:30 +0x439
github.com/tomwassing/x/pkg/storage/postgres.Test_postgresClient_CreateX.func1(0xc00036e200)
	/Users/tom/git/x/pkg/storage/postgres/x_test.go:96 +0x184
testing.tRunner(0xc00036e200, 0xc000308520)
	/usr/local/Cellar/go/1.12.7/libexec/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.12.7/libexec/src/testing/testing.go:916 +0x35a
```

**Comment by tomwassing** [comment]
Panic was caused by the implementation of the type. Excuse me!
