### ISSUE TITLE
Using onConnect with SinglePool and context leads to panic

### ISSUE THREAD

**Issue by tbe** [go-pg/pg#1353]
In one of our projects, an PostgreSQL exporter for prometheus, we create a DB Pool with the size of one. If we use both, context aware queries AND an `onConnect` handler, the process dies with an sigsegv:

```
goroutine 127 [running]:
github.com/go-pg/pg/internal/pool.(*SingleConnPool).NewConn(0xc0002c3560, 0xc000230780, 0xc000036210, 0xc000308a80)
        /home/tberger/repos/go/pg-exporter/vendor/github.com/go-pg/pg/internal/pool/pool_single.go:51 +0x4b
github.com/go-pg/pg.(*baseDB).cancelRequest(0xc0000c5360, 0xa987488a00003d0b, 0x0, 0x0)
        /home/tberger/repos/go/pg-exporter/vendor/github.com/go-pg/pg/base.go:447 +0x62
github.com/go-pg/pg.(*baseDB).withConn.func1(0xc00012c420, 0xde2440, 0xc000036200, 0xc0000c5360, 0xc000238600)
        /home/tberger/repos/go/pg-exporter/vendor/github.com/go-pg/pg/base.go:135 +0x16e
created by github.com/go-pg/pg.(*baseDB).withConn
        /home/tberger/repos/go/pg-exporter/vendor/github.com/go-pg/pg/base.go:131 +0x18a
```

We don't reuse the pool. The Scrape handler creates a new pool on each run and closes it at the end. But the segfault only occurs on the second scrape.

**Comment by vmihailenco** [comment]
Please try to upgrade to latest master - that code changed a lot there.

**Comment by tbe** [comment]
Still happens on the latest v9 rc:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6e4ad9]

goroutine 169 [running]:
github.com/go-pg/pg/v9/internal/pool.(*SingleConnPool).NewConn(0xc000571560, 0xadbf40, 0xc0000b4018, 0xc0002e3780, 0xc0002e3700, 0x4d3d9d)
        /home/tberger/go/pkg/mod/github.com/go-pg/pg/v9@v9.0.0-beta.7/internal/pool/pool_single.go:62 +0x29
github.com/go-pg/pg/v9.(*baseDB).cancelRequest(0xc000188540, 0x82b9d51f00007a46, 0x0, 0x0)
        /home/tberger/go/pkg/mod/github.com/go-pg/pg/v9@v9.0.0-beta.7/base.go:474 +0x5e
github.com/go-pg/pg/v9.(*baseDB).withConn.func1(0xc0004d05a0, 0xadbf00, 0xc00021c940, 0xc000188540, 0xc000188480)
        /home/tberger/go/pkg/mod/github.com/go-pg/pg/v9@v9.0.0-beta.7/base.go:141 +0x105
created by github.com/go-pg/pg/v9.(*baseDB).withConn
        /home/tberger/go/pkg/mod/github.com/go-pg/pg/v9@v9.0.0-beta.7/base.go:137 +0x19a
exit status 2
```

**Comment by vmihailenco** [comment]
Okay, how can I reproduce this?

**Comment by tbe** [comment]
> Okay, how can I reproduce this?

Working on a minimal example

**Comment by tbe** [comment]
I'm still on it, but other projects required more of my time. I hope i can deliver the minimal example next week

**Comment by xakep666** [comment]
I've reproduced this on v9.1.6
Code 
```go
package main

import (
	"context"
	"flag"
	"time"

	"github.com/go-pg/pg/v9"
)

func main() {
	pgDSN := flag.String("pg-dsn", "postgres://postgres:pass@localhost:5432/postgres?sslmode=disable", "Postgres connection string")
	flag.Parse()

	pgOpts, err := pg.ParseURL(*pgDSN)
	if err != nil {
		panic(err)
	}

	pgOpts.OnConnect = func(conn *pg.Conn) error {
		_, err := conn.Exec("SELECT pg_sleep(10)")
		return err
	}
	db := pg.Connect(pgOpts)

	// context.WithTimeout/WithDeadline sets i/o deadline and error can't be reproduced
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		time.Sleep(500 * time.Millisecond)
		cancel()
	}()

	_, err = db.ExecContext(ctx, "SELECT 1")
	if err != nil {
		panic(err)
	}
}
```
Prints 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1143929]

goroutine 18 [running]:
github.com/go-pg/pg/v9/internal/pool.(*SingleConnPool).NewConn(0xc000208090, 0x14512c0, 0xc00001e0b0, 0x0, 0xc00017c688, 0xc00017c738)
       /sources/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.6/internal/pool/pool_single.go:66 +0x29
github.com/go-pg/pg/v9.(*baseDB).cancelRequest(0xc0002000a0, 0x6ac4cb8c00000069, 0x0, 0x0)
       /sources/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.6/base.go:482 +0x76
github.com/go-pg/pg/v9.(*baseDB).withConn.func1(0xc000236000, 0x1451280, 0xc0000212c0, 0xc0002000a0, 0xc000200050)
       /sources/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.6/base.go:145 +0x105
created by github.com/go-pg/pg/v9.(*baseDB).withConn
       /sources/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.6/base.go:141 +0x1e9
```
