### ISSUE TITLE
AfterSelect Hooks at has many relational

### ISSUE THREAD

**Issue by alam157** [go-pg/pg#1528]
I'm trying using after select in has many relational. and i get this error

```
panic: reflect: call of reflect.Value.Len on zero Value

goroutine 24 [running]:
reflect.Value.Len(0x0, 0x0, 0x0, 0x142e083)
        /usr/local/go/src/reflect/value.go:1086 +0x1ae
github.com/go-pg/pg/orm.callHookSlice2(0x18ba4c0, 0xc0000a8000, 0x0, 0x0, 0x0, 0x1, 0x17d7968, 0xc0000682c0, 0x1795700)
        /Users/firmanalamsyah/Documents/go/src/github.com/go-pg/pg/orm/hook.go:75 +0x6b
github.com/go-pg/pg/orm.callAfterSelectHookSlice(...)
        /Users/firmanalamsyah/Documents/go/src/github.com/go-pg/pg/orm/hook.go:128
github.com/go-pg/pg/orm.(*sliceTableModel).AfterSelect(0xc00006a000, 0x18ba4c0, 0xc0000a8000, 0x0, 0x0)
        /Users/firmanalamsyah/Documents/go/src/github.com/go-pg/pg/orm/model_table_slice.go:113 +0xa3
github.com/go-pg/pg/orm.(*Query).Select(0xc0004083c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/firmanalamsyah/Documents/go/src/github.com/go-pg/pg/orm/query.go:835 +0x18e
github.com/go-pg/pg/orm.(*join).selectMany(0xc0003760d0, 0x18abf00, 0xc0001f22e0, 0xc0004083c0, 0x1793b01, 0xc0004083c0)
        /Users/firmanalamsyah/Documents/go/src/github.com/go-pg/pg/orm/join.go:43 +0x6c
github.com/go-pg/pg/orm.(*join).Select(0xc0003760d0, 0x18abf00, 0xc0001f22e0, 0xc0004083c0, 0x0, 0x0)
        /Users/firmanalamsyah/Documents/go/src/github.com/go-pg/pg/orm/join.go:28 +0xa9
github.com/go-pg/pg/orm.(*Query).selectJoins(0xc0004081e0, 0xc000376000, 0x3, 0x4, 0xc0001cae10, 0x1742800)
        /Users/firmanalamsyah/Documents/go/src/github.com/go-pg/pg/orm/query.go:988 +0x17a
github.com/go-pg/pg/orm.(*Query).Select(0xc0004081e0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/firmanalamsyah/Documents/go/src/github.com/go-pg/pg/orm/query.go:829 +0x1ed
tanijoy/credit-officer-service/services/api/v1.(*BorrowerCheckingService).GetLegalCheck(0xc00027e480, 0x0, 0x0)
        /Users/firmanalamsyah/Documents/go/src/tanijoy/credit-officer-service/services/api/v1/borrower.go:78 +0x24e
tanijoy/credit-officer-service/controllers/api/v1.GetLegalChecking.func3(0xc00027e480, 0xc0001fe000, 0xc000306940)
        /Users/firmanalamsyah/Documents/go/src/tanijoy/credit-officer-service/controllers/api/v1/borrower.go:107 +0x2f
created by tanijoy/credit-officer-service/controllers/api/v1.GetLegalChecking
        /Users/firmanalamsyah/Documents/go/src/tanijoy/credit-officer-service/controllers/api/v1/borrower.go:106 +0x230
exit status 2
```
and below is my code
```
type BorrowerChecking struct {
	tableName struct{} `pg:"borrower_checking"`
	BaseModel
	ID                      int64
	AdditionalDocs          []*CoAdditionalDoc        `pg:"fk:borrower_check_id"`
}

func (b *BorrowerChecking) AfterSelect(ctx context.Context) error {
	if b.AdditionalDocs != nil {
		for _, additionalDoc := range b.AdditionalDocs {
			_ = additionalDoc.AfterSelect(ctx)
		}
	}
	return nil
}

type CoAdditionalDoc struct {
	BaseModel
	ID              int64
	BorrowerCheckID int64
	NameDocs        string
	Path            string
}

func (c *CoAdditionalDoc) AfterSelect(ctx context.Context) error {
	if c.Path != "" {
		c.Path = os.Getenv("OSS_URL") + "/" + c.Path
	}
	return nil
}
```

anyithing wrong with my code?
thanks for helping

**Comment by vmihailenco** [comment]
Please provide a program that reproduces the problem. It is hard to say anything by the code you've provided.

**Comment by Janther** [comment]
I'm having the same issue.

I hope this case helps:

```Golang
type (
	User struct {
		ID   int `pg:",pk"`
		Roles []* Role `pg:"many2many:role_to_users"`
	}

	Role struct {
		ID     int `pg:",pk"`
		Users []*User `pg:"many2many:role_to_users"`
	}
)

func (u *User) AfterSelect(ctx context.Context) error {
	return nil
}

users := User{}
db.Model(&user).Relation("Roles").First() // Ok

roles := []Role{}
db.Model(&role).Relation("Users"). First() // Panics
```

```
reflect: call of reflect.Value.Len on zero Value

reflect.Value.Len(0x0, 0x0, 0x0, 0x14a02d3)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/reflect/value.go:1140 +0x17f
github.com/go-pg/pg/v9/orm.callHookSlice2(0x1b99dc0, 0xc000134008, 0x0, 0x0, 0x0, 0x1, 0x1a82fd0, 0xc000230800, 0x1969160)
	/Users/klaushottvidal/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.2/orm/hook.go:75 +0x6b
github.com/go-pg/pg/v9/orm.callAfterSelectHookSlice(...)
	/Users/klaushottvidal/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.2/orm/hook.go:128
github.com/go-pg/pg/v9/orm.(*sliceTableModel).AfterSelect(0xc0004a46c0, 0x1b99dc0, 0xc000134008, 0x0, 0x0)
	/Users/klaushottvidal/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.2/orm/model_table_slice.go:113 +0xa1
github.com/go-pg/pg/v9/orm.(*Query).Select(0xc000b363c0, 0x0, 0x0, 0x0, 0xc000b363c0, 0x0)
	/Users/klaushottvidal/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.2/orm/query.go:835 +0x189
github.com/go-pg/pg/v9/orm.(*join).selectM2M(0xc0002b2230, 0x1b8b160, 0xc000090b40, 0xc000b363c0, 0x1967c01, 0xc000b363c0)
	/Users/klaushottvidal/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.2/orm/join.go:97 +0x80
github.com/go-pg/pg/v9/orm.(*join).Select(0xc0002b2230, 0x1b8b160, 0xc000090b40, 0xc000b363c0, 0xc0008271e0, 0x0)
	/Users/klaushottvidal/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.2/orm/join.go:30 +0x64
github.com/go-pg/pg/v9/orm.(*Query).selectJoins(0xc000b361e0, 0xc0002b2230, 0x1, 0x1, 0xc0004a4600, 0x1914a00)
	/Users/klaushottvidal/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.2/orm/query.go:988 +0x179
github.com/go-pg/pg/v9/orm.(*Query).Select(0xc000b361e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/klaushottvidal/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.2/orm/query.go:829 +0x1e2
```

This is the most simple scenario and it fails when the Relation has an AfterSelect hook in my case.

**Comment by Janther** [comment]
My scenario is a many2many Relation but I believe the bug is the same.

**Comment by Janther** [comment]
updating to `v9.1.6` solved this :)
