### ISSUE TITLE
Changes in pointer struct embedding in the latest version?

### ISSUE THREAD

**Issue by ganigeorgiev** [go-pg/pg#1741]
Just updated to 10.2.0 and some of my queries no longer works. The following panic is thrown when I try to `Select` a single model with an embedded pointer struct:

```
panic: reflect: reflect.Value.Set using value obtained using unexported field

goroutine 1 [running]:
reflect.flag.mustBeAssignableSlow(0x1d6)
    /usr/local/go/src/reflect/value.go:256 +0x1b9
reflect.flag.mustBeAssignable(...)
    /usr/local/go/src/reflect/value.go:246
reflect.Value.Set(0x96e700, 0xc0000b6000, 0x1d6, 0x96e700, 0xc0000adac0, 0x16)
    /usr/local/go/src/reflect/value.go:1548 +0x3b
github.com/go-pg/pg/v10/orm.indirectNil(0x96e700, 0xc0000b6000, 0x1d6, 0x0, 0x96e700, 0xc0000b6000)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/orm/util.go:84 +0x11e
github.com/go-pg/pg/v10/orm.fieldByIndexAlloc(0x9d1fa0, 0xc0000b6000, 0x199, 0xc0000ba0a0, 0x2, 0x2, 0xc0000bba28, 0x2, 0xc0000e0c38)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/orm/util.go:74 +0xa8
github.com/go-pg/pg/v10/orm.(*Field).Value(...)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/orm/field.go:69
github.com/go-pg/pg/v10/orm.(*Field).ScanValue(0xc0000c2000, 0x9d1fa0, 0xc0000b6000, 0x199, 0xa8a800, 0xc0000b0060, 0x24, 0x7f52a3d764d8, 0x8f83e3)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/orm/field.go:109 +0x6c
github.com/go-pg/pg/v10/orm.(*structTableModel).scanColumn(0xc0000e6000, 0xb8600000000, 0xc0000bba28, 0x2, 0xa8a800, 0xc0000b0060, 0x24, 0xc0000b0000, 0x4, 0xc000280266)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/orm/model_table_struct.go:298 +0x14c
github.com/go-pg/pg/v10/orm.(*structTableModel).ScanColumn(0xc0000e6000, 0xb8600000000, 0xc0000bba28, 0x2, 0xa8a800, 0xc0000b0060, 0x24, 0x0, 0x0)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/orm/model_table_struct.go:252 +0x8b
github.com/go-pg/pg/v10.readDataRow(0xa86ae0, 0xc0000220e8, 0xc0000b2000, 0xc0000e8000, 0x15, 0x20, 0xa7d040, 0xc0000e6000, 0xc000158680, 0x0)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/messages.go:811 +0x231
github.com/go-pg/pg/v10.readSimpleQueryData(0xa86ae0, 0xc0000220e8, 0xc0000b2000, 0x9cdbc0, 0xc0000e6000, 0x9673e0, 0x9c53e0, 0xd72900)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/messages.go:873 +0x2fc
github.com/go-pg/pg/v10.(*baseDB).simpleQueryData.func1(0xc0000b2000, 0xa8a560, 0xc000094008)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/base.go:585 +0x5c
github.com/go-pg/pg/v10/internal/pool.(*Conn).WithReader.func1(0xa86ae0, 0xc0000220e8, 0xa8b260, 0xda3720, 0x0, 0x0)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/internal/pool/conn.go:96 +0x10f
github.com/go-pg/pg/v10/internal.WithSpan(0xa86ae0, 0xc0000220e8, 0x9e26b4, 0xb, 0xc0001696d0, 0x0, 0x0)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/internal/util.go:84 +0x247
github.com/go-pg/pg/v10/internal/pool.(*Conn).WithReader(0xc000092050, 0xa86ae0, 0xc0000220e8, 0x0, 0xc000169740, 0x0, 0x0)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/internal/pool/conn.go:80 +0x95
github.com/go-pg/pg/v10.(*baseDB).simpleQueryData(0xc000200640, 0xa86ae0, 0xc0000220e8, 0xc000092050, 0x9cdbc0, 0xc0000e6000, 0xc000098060, 0xc0000ada40, 0xa7cea0, 0xc0000e4140)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/base.go:583 +0x12b
github.com/go-pg/pg/v10.(*baseDB).query.func1.1(0xa86ae0, 0xc0000220e8, 0xc000092050, 0xc000092050, 0x0)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/base.go:332 +0x7c
github.com/go-pg/pg/v10.(*baseDB).withConn.func1(0xa86ae0, 0xc0000220e8, 0xa8b260, 0xda3720, 0x0, 0x0)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/base.go:175 +0x133
github.com/go-pg/pg/v10/internal.WithSpan(0xa86ae0, 0xc0000220e8, 0x9e1918, 0x9, 0xc000169980, 0x0, 0x0)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/internal/util.go:84 +0x247
github.com/go-pg/pg/v10.(*baseDB).withConn(0xc000200640, 0xa86ae0, 0xc0000220e8, 0xc000169a48, 0xc000169a58, 0x203000)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/base.go:142 +0x89
github.com/go-pg/pg/v10.(*baseDB).query.func1(0xa86ae0, 0xc0000220e8, 0xa8b260, 0xda3720, 0x0, 0x0)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/base.go:331 +0xf2
github.com/go-pg/pg/v10/internal.WithSpan(0xa86ae0, 0xc0000220e8, 0x9dfbf6, 0x5, 0xc000169ca0, 0x0, 0x0)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/internal/util.go:84 +0x247
github.com/go-pg/pg/v10.(*baseDB).query(0xc000200640, 0xa86ae0, 0xc0000220e8, 0x9cdbc0, 0xc0000e6000, 0x9a4b20, 0xc0000e4120, 0xc0000b31e0, 0x1, 0x1, ...)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/base.go:322 +0x399
github.com/go-pg/pg/v10.(*baseDB).QueryContext(...)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/base.go:301
github.com/go-pg/pg/v10.(*baseDB).queryOne(0xc000200640, 0xa86ae0, 0xc0000220e8, 0x9cdbc0, 0xc0000e6000, 0x9a4b20, 0xc0000e4120, 0xc0000b31e0, 0x1, 0x1, ...)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/base.go:363 +0xb5
github.com/go-pg/pg/v10.(*baseDB).QueryOneContext(0xc000200640, 0xa86ae0, 0xc0000220e8, 0x9cdbc0, 0xc0000e6000, 0x9a4b20, 0xc0000e4120, 0xc0000b31e0, 0x1, 0x1, ...)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/base.go:359 +0xa7
github.com/go-pg/pg/v10/orm.(*Query).query(0xc0000b8000, 0xa86ae0, 0xc0000220e8, 0xa8af60, 0xc0000e6000, 0x9a4b20, 0xc0000e4120, 0x0, 0x1, 0xc0000b31d0, ...)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/orm/query.go:867 +0x127
github.com/go-pg/pg/v10/orm.(*Query).Select(0xc0000b8000, 0x0, 0x0, 0x0, 0x1, 0x1)
    /home/***/projects/go/pkg/mod/github.com/go-pg/pg/v10@v10.2.0/orm/query.go:838 +0xfe
main.main()
    /home/***/projects/***/api/main.go:32 +0x152
exit status 2
```

Here is my model struct:

```go
type Account struct {
    *baseModel

    CompanyId uuid.UUID
    Status    string
    Type      string
    Email     string
    // ... other fields

    // relations
    Company   *Company   `pg:"rel:has-one"`
}
```

An example call:
```go
account := new(models.Account)
db.Model(account).Where("email = ?", "test@example.com").Select()
```

The error seems to be in the private embedded pointer struct - `*baseModel`. If I change that to just `baseModel` or make it public (aka. `*BaseModel`) my query executes successfully.

Is this behavior intentional (in the early beta 5-6 version the issue doesn't occur)?

**Comment by vmihailenco** [comment]
I am not sure whether this should work or not. If you can provide an example that I can run - I will dig further.

**Comment by ganigeorgiev** [comment]
@vmihailenco I'm sorry. I've realized that the panic is not caused by go-pg update; it's because of a change related to our app - in earlier versions we didn't need a pointer to the embedded struct.

The issue here is that with reflection I don't think it is possible to create an instance to an external unexported struct (It works with the embedded value struct, aka. `baseModel`, because I believe it is created with its default zero value on Account instance creation). Similar issue is described in [encoding/json-#21357](https://github.com/golang/go/issues/21357). 

I'm closing the issue, since fixing it at app level is easier (just export the embedded pointer struct) and I'm not sure that actually this could be fixed in go-pg (there is also a change with the reflect package policy with go v1.10+).
