### ISSUE TITLE
Cannot get sql.Null* values to persist in the database

### ISSUE THREAD

**Issue by mylanconnolly** [go-pg/pg#204]
Hello,

I am attempting to get the sql.Null values to work (specifically `sql.NullInt64`) properly with `pg` because I am working with a database that has null values in some columns. Originally, I was planning just using the type `*int64`, however I get a panic like the following:

```
panic: reflect: call of reflect.Value.Int on ptr Value

goroutine 1 [running]:
panic(0x6c9880, 0xc8203f0de0)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
reflect.Value.Int(0x653a00, 0xc82013c008, 0x196, 0x1)
	/usr/lib/go/src/reflect/value.go:891 +0xa6
gopkg.in/pg.v4/types.appendIntValue(0xc820408000, 0x98, 0x2000, 0x653a00, 0xc82013c008, 0x196, 0x1, 0x0, 0x0, 0x0)
	/home/mylanc/go/src/gopkg.in/pg.v4/types/append_value.go:93 +0x53
gopkg.in/pg.v4/orm.(*Field).AppendValue(0xc8202d4bd0, 0xc820408000, 0x98, 0x2000, 0x719160, 0xc82013c000, 0x199, 0x1, 0x0, 0x0, ...)
	/home/mylanc/go/src/gopkg.in/pg.v4/orm/field.go:63 +0x294
gopkg.in/pg.v4/orm.insertQuery.AppendQuery(0xc8200146e0, 0xc820408000, 0x98, 0x2000, 0xc8203ea900, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/home/mylanc/go/src/gopkg.in/pg.v4/orm/insert.go:51 +0x942
gopkg.in/pg%2ev4.appendQuery(0xc820408000, 0x5, 0x2000, 0x729860, 0xc8200146e0, 0xc8203ea900, 0x1, 0x1, 0x0, 0x0, ...)
	/home/mylanc/go/src/gopkg.in/pg.v4/messages.go:257 +0x13c
gopkg.in/pg%2ev4.writeQueryMsg(0xc820404280, 0x729860, 0xc8200146e0, 0xc8203ea900, 0x1, 0x1, 0x0, 0x0)
	/home/mylanc/go/src/gopkg.in/pg.v4/messages.go:243 +0x153
gopkg.in/pg%2ev4.simpleQueryData(0xc8203ef9d0, 0x6f3540, 0xc8203ea910, 0x729860, 0xc8200146e0, 0xc8203ea900, 0x1, 0x1, 0x7faff9cd8508, 0x0, ...)
	/home/mylanc/go/src/gopkg.in/pg.v4/db.go:310 +0x7c
gopkg.in/pg%2ev4.(*DB).Query(0xc820120af0, 0x6f3540, 0xc8203ea910, 0x729860, 0xc8200146e0, 0xc8203ea900, 0x1, 0x1, 0x0, 0x0, ...)
	/home/mylanc/go/src/gopkg.in/pg.v4/db.go:150 +0xf2
gopkg.in/pg%2ev4.(*DB).QueryOne(0xc820120af0, 0x71b480, 0xc8203ef810, 0x729860, 0xc8200146e0, 0xc8203ea900, 0x1, 0x1, 0x17, 0x0, ...)
	/home/mylanc/go/src/gopkg.in/pg.v4/db.go:173 +0xf4
gopkg.in/pg.v4/orm.Create(0x7faff9cd43f0, 0xc820120af0, 0x653f40, 0xc82013c000, 0x0, 0x0)
	/home/mylanc/go/src/gopkg.in/pg.v4/orm/insert.go:13 +0x1d3
gopkg.in/pg%2ev4.(*DB).Create(0xc820120af0, 0x653f40, 0xc82013c000, 0x0, 0x0)
	/home/mylanc/go/src/gopkg.in/pg.v4/db.go:250 +0x6c
main.main()
	/home/mylanc/go/src/git.iotrak.net/intra-frameworks/intra-test/main.go:91 +0x137
```

So I resorted to the `sql.NullInt64` data type, and attempted to use it like so in a test (note that the source here is greatly simplified):

```go
package main

type Client struct {
	TableName     struct{} `sql:"clients"`
	ID            int64
	InsertedByID  sql.NullInt64
	InsertedBy    *User `pg:",fk:InsertedBy" sql:",null"`
	UpdatedByID   sql.NullInt64
	UpdatedBy     *User `pg:",fk:UpdatedBy" sql:",null"`
	ClientGroupID int64
	ClientGroup   *ClientGroup `pg:",fk:ClientGroup"`
	ClientTypeID  int64
	ClientType    *ClientType   `pg:",fk:ClientType"`
	LegacyPK      sql.NullInt64
	Name          string
	Description   string
	Info          map[string]interface{}
	InsertedAt    time.Time `sql:",null"`
	UpdatedAt     time.Time `sql:",null"`
}

func main() {
	// Set up database connection, etc...
	c := Client{
		Name:          "Test client type",
		Description:   "Test client type!",
		ClientGroupID: 1057738917706466306,
		ClientTypeID:  1057738917664523265,
		LegacyPK:      sql.NullInt64{Int64: 123456789, Valid: true},
	}
	err := db.Create(&c)
	if err != nil {
		log.Fatal(err.Error())
	}
}
```

I do not receive any errors, however in the PostgreSQL log I see that the "legacy_pk" column (corresponding to `LegacyPK` field) is not in the `INSERT` query.

Am I doing something wrong or is there something strange about the sql.NullInt64 data type? I couldn't find much in the way of documentation or tests relating to this specifically, although I saw there is a mapping test to `BIGINT` which seemed promising, but I'm not sure if a struct tag needs to be used or not.

Thanks!

**Comment by vmihailenco** [comment]
Hi,

Thanks for the detailed report. I think I fixed both `sql.NullInt64` and `*int64` in v4.1.3. Please try it.

Also I think you can remove `TableName     struct{} `sql:"clients"` and all `pg:",fk:ClientType"`. Those annotations are only needed when you want to use custom naming.

**Comment by mylanconnolly** [comment]
Updated and tried it out; looks like the fix worked. Thanks!

Also thanks for the tip on TableName. At the time I wasn't sure how well the inflection worked, but I looked through the source code to see how it determined the name and it actually lines up for the vast majority of my models. Thanks again, this library is quite good!
