### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by matthewvalimaki** [go-pg/pg#412]
The below error comes up when I do `OrderExpr` with `Group` and couple sub queries, really after adding `Group` did the error come up. Details at this time, such code I am executing, are not here and I am working on those. I wanted to create this issue in case someone can spot where in code this happens. I am trying to bring down the complexity of the query so that it's easier to understand.

```
panic: runtime error: index out of range

goroutine 32 [running]:
panic(0x7f49058f1da0, 0xc4200140a0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
gopkg.in/pg.v5/orm.valuesModel.ScanColumn(0xc4204f3140, 0x1, 0x1, 0x1, 0xc4204f37d0, 0xd, 0xc420386000, 0x1, 0x2000, 0x0, ...)
	/home/test/lib/go/src/gopkg.in/pg.v5/orm/model_scan.go:66 +0x9f
gopkg.in/pg.v5/orm.(*valuesModel).ScanColumn(0xc4204fbd40, 0x1, 0xc4204f37d0, 0xd, 0xc420386000, 0x1, 0x2000, 0x0, 0x0)
	<autogenerated>:15 +0xb2
gopkg.in/pg%2ev5.readDataRow(0xc42029e280, 0x7f4905b9e9e0, 0xc4204fbd40, 0xc4202f31e0, 0x7, 0x7, 0x0, 0x0)
	/home/test/lib/go/src/gopkg.in/pg.v5/messages.go:624 +0x1a3
gopkg.in/pg%2ev5.readSimpleQueryData(0xc42029e280, 0x7f4905967ee0, 0xc4204fb180, 0x7f4905985ea0, 0xc42026fce0, 0xc4204f3150, 0x0, 0x0)
	/home/test/lib/go/src/gopkg.in/pg.v5/messages.go:679 +0x2dc
gopkg.in/pg%2ev5.(*DB).simpleQueryData(0xc4202181a0, 0xc42029e280, 0x7f4905967ee0, 0xc4204fb180, 0x7f4905985ea0, 0xc42026fce0, 0xc4204f3150, 0x1, 0x1, 0x7f4905bbf4a0, ...)
	/home/test/lib/go/src/gopkg.in/pg.v5/db.go:370 +0xe2
gopkg.in/pg%2ev5.(*DB).Query(0xc4202181a0, 0x7f4905967ee0, 0xc4204fb180, 0x7f4905985ea0, 0xc42026fce0, 0xc4204f3150, 0x1, 0x1, 0xc4202c36a8, 0x7f490519323d, ...)
	/home/test/lib/go/src/gopkg.in/pg.v5/db.go:197 +0xf1
gopkg.in/pg%2ev5.(*DB).QueryOne(0xc4202181a0, 0x7f4905967ee0, 0xc4204fb180, 0x7f4905985ea0, 0xc42026fce0, 0xc4204f3150, 0x1, 0x1, 0x0, 0xc4202c3760, ...)
	/home/test/lib/go/src/gopkg.in/pg.v5/db.go:231 +0x10b
gopkg.in/pg.v5/orm.(*Query).Count(0xc42026fce0, 0x7f490598a600, 0xc4204f3120, 0x0)
	/home/test/lib/go/src/gopkg.in/pg.v5/orm/query.go:285 +0x2ee
gopkg.in/pg.v5/orm.(*Query).SelectAndCount.func2(0xc4204f3120, 0xc4204f3100, 0xc42026e420, 0xc4204f3110)
	/home/test/lib/go/src/gopkg.in/pg.v5/orm/query.go:366 +0x59
created by gopkg.in/pg.v5/orm.(*Query).SelectAndCount
	/home/test/lib/go/src/gopkg.in/pg.v5/orm/query.go:370 +0x1be
```

**Comment by vmihailenco** [comment]
Such panic happens when you use `pg.Scan(&var1, var2)` or `Select(&var1, &var2)` and query returns more columns than variables to scan.
