### ISSUE TITLE
override fails with call of reflect.Value.SetInt on string Value

### ISSUE THREAD

**Issue by martoche** [go-pg/pg#547]
I've stumbled on the following bug.

It began by panics in production only (arm/linux server), but not on my development machine (darwin/amd64):

````
May 23 07:53:24 backend[29739]: 2017/05/23 07:53:24 reflect: Field index out of range
May 23 07:53:24 backend[29739]: goroutine 20 [running]:
May 23 07:53:24 backend[29739]: runtime/debug.Stack(0x3cd54c, 0x10a160f0, 0x2)
May 23 07:53:24 backend[29739]:         /opt/local/lib/go/src/runtime/debug/stack.go:24 +0x58
May 23 07:53:24 backend[29739]: runtime/debug.PrintStack()
May 23 07:53:24 backend[29739]:         /opt/local/lib/go/src/runtime/debug/stack.go:16 +0x14
May 23 07:53:24 backend[29739]: main.PanicHandler(0x6b3d10, 0x10b5a510, 0x10b4c780, 0x42a7d0, 0x10b4afc8)
May 23 07:53:24 backend[29739]:         /tmp/superg/server.go:17 +0x48
May 23 07:53:24 backend[29739]: github.com/julienschmidt/httprouter.(*Router).recv(0x10b48060, 0x6b3d10, 0x10b5a510, 0x10b4c780)
May 23 07:53:24 backend[29739]:         /Users/martin/go/src/github.com/julienschmidt/httprouter/router.go:280 +0x60
May 23 07:53:24 backend[29739]: panic(0x42a7d0, 0x10b4afc8)
May 23 07:53:24 backend[29739]:         /opt/local/lib/go/src/runtime/panic.go:489 +0x288
May 23 07:53:24 backend[29739]: reflect.Value.Field(0x43df58, 0x10dc85a0, 0x199, 0x10, 0x0, 0x0, 0x27)
May 23 07:53:24 backend[29739]:         /opt/local/lib/go/src/reflect/value.go:763 +0x100
May 23 07:53:24 backend[29739]: github.com/go-pg/pg/orm.(*sliceTableModel).Bind(0x10df6280, 0x43df58, 0x10dc85a0, 0x199)
May 23 07:53:24 backend[29739]:         /Users/martin/go/src/github.com/go-pg/pg/orm/model_table_slice.go:32 +0x118
May 23 07:53:24 backend[29739]: github.com/go-pg/pg/orm.(*structTableModel).bindChildren(0x10b6e5a0)
May 23 07:53:24 backend[29739]:         /Users/martin/go/src/github.com/go-pg/pg/orm/model_table_struct.go:127 +0x3c8
May 23 07:53:24 backend[29739]: github.com/go-pg/pg/orm.(*sliceTableModel).NewModel(0x10b6e5a0, 0x10b6e544, 0xbc)
May 23 07:53:24 backend[29739]:         /Users/martin/go/src/github.com/go-pg/pg/orm/model_table_slice.go:48 +0x60
May 23 07:53:24 backend[29739]: github.com/go-pg/pg.readSimpleQueryData(0x10b11ec0, 0x488eb0, 0x10b6e5a0, 0x472a58, 0x10df5060, 0x10b4af50)
May 23 07:53:24 backend[29739]:         /Users/martin/go/src/github.com/go-pg/pg/messages.go:633 +0x1cc
May 23 07:53:24 backend[29739]: github.com/go-pg/pg.(*DB).simpleQueryData(0x10b19100, 0x10b11ec0, 0x488eb0, 0x10b6e5a0, 0x472a58, 0x10df5060, 0x10b4af50, 0x1, 0x1, 0x8, ...)
May 23 07:53:24 backend[29739]:         /Users/martin/go/src/github.com/go-pg/pg/db.go:367 +0xa0
May 23 07:53:24 backend[29739]: github.com/go-pg/pg.(*DB).Query(0x10b19100, 0x488eb0, 0x10b6e5a0, 0x472a58, 0x10df5060, 0x10b4af50, 0x1, 0x1, 0x10a5bd28, 0xc, ...)
May 23 07:53:24 backend[29739]:         /Users/martin/go/src/github.com/go-pg/pg/db.go:190 +0x190
May 23 07:53:24 backend[29739]: github.com/go-pg/pg/orm.(*Query).query(0x10b602c0, 0x6b5f90, 0x10b6e5a0, 0x472a58, 0x10df5060, 0x10b6e5a0, 0x0, 0x0, 0x10b602f4)
May 23 07:53:24 backend[29739]:         /Users/martin/go/src/github.com/go-pg/pg/orm/query.go:377 +0x1e4
May 23 07:53:24 backend[29739]: github.com/go-pg/pg/orm.(*Query).Select(0x10b602c0, 0x0, 0x0, 0x0, 0x10b602c0, 0x0)
May 23 07:53:24 backend[29739]:         /Users/martin/go/src/github.com/go-pg/pg/orm/query.go:347 +0xc4
`````

I've narrowed the bug to this single file of code:

```
// GOOS=linux GOARCH=arm go build bug.go && scp bug superg@vercors.marlentin.fr
// PGDATABASE="superg" PGNETWORK="unix" PGPASSWORD="" PGUSER="superg" ./bug

package main

import (
	"github.com/go-pg/pg"
	"os"
)

type Invoice struct {
	Id        int
	RefPrefix string
}

type AbbrInvoice struct {
	Invoice `pg:",override"`
}

func main() {
	DB := pg.Connect(&pg.Options{
		Network:  os.Getenv("PGNETWORK"),
		Addr:     os.Getenv("PGHOST"),
		User:     os.Getenv("PGUSER"),
		Password: os.Getenv("PGPASSWORD"),
		Database: os.Getenv("PGDATABASE"),
	})

	invoices := make([]*AbbrInvoice, 0)

	DB.Model(&invoices).Select()
}
````

Which produces the following crash on arm/linux only, not on darwin/amd64:

```
panic: reflect: call of reflect.Value.SetInt on string Value

goroutine 1 [running]:
reflect.Value.SetInt(0x214e78, 0x10936034, 0x198, 0x1c, 0x0)
	/opt/local/lib/go/src/reflect/value.go:1423 +0xac
github.com/go-pg/pg/types.scanIntValue(0x214e78, 0x10936034, 0x198, 0x10930000, 0x2, 0x200, 0x214e78, 0x10936034)
	/Users/martin/go/src/github.com/go-pg/pg/types/scan_value.go:165 +0xc8
github.com/go-pg/pg/orm.(*Field).ScanValue(0x108ba190, 0x21d988, 0x10936030, 0x199, 0x10930000, 0x2, 0x200, 0x2, 0x0)
	/Users/martin/go/src/github.com/go-pg/pg/orm/field.go:71 +0x88
github.com/go-pg/pg/orm.(*structTableModel).scanColumn(0x1068edc0, 0x0, 0x10936010, 0x2, 0x10930000, 0x2, 0x200, 0x10930000, 0x2, 0x200)
	/Users/martin/go/src/github.com/go-pg/pg/orm/model_table_struct.go:223 +0xe4
github.com/go-pg/pg/orm.(*structTableModel).ScanColumn(0x1068edc0, 0x0, 0x10936010, 0x2, 0x10930000, 0x2, 0x200, 0x0, 0x0)
	/Users/martin/go/src/github.com/go-pg/pg/orm/model_table_struct.go:199 +0x4c
github.com/go-pg/pg.readDataRow(0x107d4180, 0x340ab0, 0x1068edc0, 0x10938020, 0x2, 0x2, 0x2, 0x0)
	/Users/martin/go/src/github.com/go-pg/pg/messages.go:580 +0x12c
github.com/go-pg/pg.readSimpleQueryData(0x107d4180, 0x23ed18, 0x1068edc0, 0x2358d0, 0x106e0b50, 0x1060d718)
	/Users/martin/go/src/github.com/go-pg/pg/messages.go:630 +0x208
github.com/go-pg/pg.(*DB).simpleQueryData(0x106c3fc0, 0x107d4180, 0x23ed18, 0x1068edc0, 0x2358d0, 0x106e0b50, 0x1060d718, 0x1, 0x1, 0x8, ...)
	/Users/martin/go/src/github.com/go-pg/pg/db.go:367 +0xa0
github.com/go-pg/pg.(*DB).Query(0x106c3fc0, 0x23ed18, 0x1068edc0, 0x2358d0, 0x106e0b50, 0x1060d718, 0x1, 0x1, 0x10635f5c, 0xc, ...)
	/Users/martin/go/src/github.com/go-pg/pg/db.go:190 +0x190
github.com/go-pg/pg/orm.(*Query).query(0x1060e160, 0x343758, 0x1068edc0, 0x2358d0, 0x106e0b50, 0x1068edc0, 0x0, 0x0, 0x343230)
	/Users/martin/go/src/github.com/go-pg/pg/orm/query.go:377 +0x1e4
github.com/go-pg/pg/orm.(*Query).Select(0x1060e160, 0x0, 0x0, 0x0, 0x1060e160, 0x0)
	/Users/martin/go/src/github.com/go-pg/pg/orm/query.go:347 +0xc4
main.main()
	/Users/martin/bug/bug.go:33 +0x268
```

My analysis is that this line (https://github.com/go-pg/pg/blob/master/orm/table.go#L269 ) in `func (t *Table) newField` is to blame:

```
Index: append(index, f.Index...),
```

The `index` variable here is a slice, whose underlying array is shared between the `Id` fields of `Invoice` and `AbbrInvoice`. So when `append(index, f.Index...)` is called for `AbbrInvoice`, there is a side effect, it also modifies the `Index` of the `Id` field of `Invoice`.

I'm not sure how the index variable ends being shared between the two fields, maybe it is resliced and something like that https://play.golang.org/p/Y6E2oHXSQD happens.

A fix for the bug consists in copying the index slice before calling `append`:

	index_copy := append([]int(nil), index...)

	field := Field{
		Type: indirectType(f.Type),

		GoName:  f.Name,
		SQLName: sqlName,
		ColName: types.Q(types.AppendField(nil, sqlName, 1)),

		Index: append(index_copy, f.Index...),
	}

Not sharing the index variable in the first place would maybe also fix the issue.

**Comment by vmihailenco** [comment]
Thanks for debugging this - should be fixed in v6.1.7
