### ISSUE TITLE
Custom data type in model struct causes runtime panic during DB.insert

### ISSUE THREAD

**Issue by dkulchenko** [go-pg/pg#679]
This works:

```go
package main

import (
	"github.com/go-pg/pg"
)

type Test struct {
	ID []byte `sql:",pk,type:uuid"`
}

func main() {
	obj := Test{
		ID: []byte("abcabcabcabcabcd"),
	}

	db := pg.Connect(&pg.Options{
		User:     "postgres",
	})

	db.Insert(&obj)
}
```

This panics at runtime during the .Insert call:

```go
package main

import (
	"math/rand"
	"time"

	"github.com/go-pg/pg"
	"github.com/oklog/ulid"
)

type Test struct {
	ID ulid.ULID `sql:",pk,type:uuid"`
}

func main() {
	t := time.Now()
	entropy := rand.New(rand.NewSource(t.UnixNano()))

	obj := Test{
		ID: ulid.MustNew(ulid.Timestamp(t), entropy),
	}

	db := pg.Connect(&pg.Options{
		User:     "postgres",
	})

	db.Insert(&obj)
}
```

The traceback is:

```
❯ go run main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1178845]

goroutine 1 [running]:
code.secretproject.com/zoom/vendor/github.com/go-pg/pg/orm.(*Field).AppendValue(0xc420244320, 0xc4203c3000, 0x28, 0x1000, 0x12a1720, 0xc42012a160, 0x199, 0x1, 0x118a230, 0x0, ...)
	/Users/daniilk/go/src/code.secretproject.com/zoom/vendor/github.com/go-pg/pg/orm/field.go:68 +0xd5
code.secretproject.com/zoom/vendor/github.com/go-pg/pg/orm.(*insertQuery).appendValues(0xc42004da08, 0xc4203c3000, 0x28, 0x1000, 0xc42000e908, 0x1, 0x1, 0x12a1720, 0xc42012a160, 0x199, ...)
	/Users/daniilk/go/src/code.secretproject.com/zoom/vendor/github.com/go-pg/pg/orm/insert.go:125 +0x2a0
code.secretproject.com/zoom/vendor/github.com/go-pg/pg/orm.insertQuery.AppendQuery(0xc420001e00, 0x0, 0x0, 0x0, 0xc4203c3000, 0x28, 0x1000, 0x1010513, 0x12a0aa0, 0x12bb920, ...)
	/Users/daniilk/go/src/code.secretproject.com/zoom/vendor/github.com/go-pg/pg/orm/insert.go:76 +0xd94
code.secretproject.com/zoom/vendor/github.com/go-pg/pg/orm.(*insertQuery).AppendQuery(0xc42012c200, 0xc4203c3000, 0x5, 0x1000, 0xc42012c200, 0xc42004da01, 0x108b9f2, 0xc42011ee80, 0x0)
	<autogenerated>:1 +0x87
code.secretproject.com/zoom/vendor/github.com/go-pg/pg.appendQuery(0xc4203c3000, 0x5, 0x1000, 0x142f940, 0xc4200e3ea0, 0x12bb920, 0xc42012c200, 0xc42010c980, 0x1, 0x1, ...)
	/Users/daniilk/go/src/code.secretproject.com/zoom/vendor/github.com/go-pg/pg/messages.go:264 +0x270
code.secretproject.com/zoom/vendor/github.com/go-pg/pg.writeQueryMsg(0xc4203be060, 0x142f940, 0xc4200e3ea0, 0x12bb920, 0xc42012c200, 0xc42010c980, 0x1, 0x1, 0x5d7dd68, 0x3f7d9a9)
	/Users/daniilk/go/src/code.secretproject.com/zoom/vendor/github.com/go-pg/pg/messages.go:250 +0xe7
code.secretproject.com/zoom/vendor/github.com/go-pg/pg.(*DB).simpleQueryData(0xc4200e3ea0, 0xc4203c6000, 0x12d1100, 0xc42011ed80, 0x12bb920, 0xc42012c200, 0xc42010c980, 0x1, 0x1, 0x10, ...)
	/Users/daniilk/go/src/code.secretproject.com/zoom/vendor/github.com/go-pg/pg/db.go:414 +0x8a
code.secretproject.com/zoom/vendor/github.com/go-pg/pg.(*DB).Query(0xc4200e3ea0, 0x12d1100, 0xc42011ed80, 0x12bb920, 0xc42012c200, 0xc42010c980, 0x1, 0x1, 0x1189408, 0x12760c0, ...)
	/Users/daniilk/go/src/code.secretproject.com/zoom/vendor/github.com/go-pg/pg/db.go:209 +0x164
code.secretproject.com/zoom/vendor/github.com/go-pg/pg/orm.(*Query).Insert(0xc420001e00, 0x0, 0x0, 0x0, 0x1, 0xc420001e00, 0x0, 0x50)
	/Users/daniilk/go/src/code.secretproject.com/zoom/vendor/github.com/go-pg/pg/orm/query.go:584 +0x1f9
code.secretproject.com/zoom/vendor/github.com/go-pg/pg/orm.Insert(0x1435120, 0xc4200e3ea0, 0xc42010c970, 0x1, 0x1, 0xc4200e3e01, 0xc42010c970)
	/Users/daniilk/go/src/code.secretproject.com/zoom/vendor/github.com/go-pg/pg/orm/insert.go:9 +0x80
code.secretproject.com/zoom/vendor/github.com/go-pg/pg.(*DB).Insert(0xc4200e3ea0, 0xc42010c970, 0x1, 0x1, 0x496da165c1f82787, 0x144ff01)
	/Users/daniilk/go/src/code.secretproject.com/zoom/vendor/github.com/go-pg/pg/db.go:345 +0x55
main.main()
	/Users/daniilk/secretproject/code/zoom/main.go:30 +0x378
exit status 2
```

ulid.ULID is just:

```go
type ULID [16]byte
```

How can I make this work?

**Comment by vmihailenco** [comment]
Should be fixed though it is marshaled as hex value, not UUID.
