### ISSUE TITLE
panic: reflect: call of reflect.Value.Field on zero Value

### ISSUE THREAD

**Issue by gadelkareem** [go-pg/pg#789]
I am getting this error while doing batch update with set
```
type book struct {
  num int64 `sql:"num,notnull,default:-1,type:BIGINT"`
}
Db.Model(&books).Set("num = ?num").Update()
```

```
panic: reflect: call of reflect.Value.Field on zero Value

goroutine 1 [running]:
reflect.Value.Field(0x0, 0x0, 0x0, 0x11, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:782 +0x11b
reflect.Value.FieldByIndex(0x0, 0x0, 0x0, 0xc4201e67e8, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:814 +0x215
github.com/go-pg/pg/orm.(*Field).Value(0xc420149500, 0x0, 0x0, 0x0, 0x7, 0x1, 0x6f00000000000000)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/orm/field.go:65 +0x5f
github.com/go-pg/pg/orm.(*Field).AppendValue(0xc420149500, 0xc420457000, 0x32, 0x1000, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/orm/field.go:78 +0x59
github.com/go-pg/pg/orm.(*Table).AppendParam(0xc42015a000, 0xc420457000, 0x32, 0x1000, 0x0, 0x0, 0x0, 0x16e52b5, 0x7, 0x0, ...)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/orm/table.go:125 +0x21f
github.com/go-pg/pg/orm.(*structTableModel).AppendParam(0xc4200d40a0, 0xc420457000, 0x32, 0x1000, 0x17420c0, 0x0, 0x16e52b5, 0x7, 0x0, 0x0, ...)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/orm/model_table_struct.go:50 +0x9f
github.com/go-pg/pg/orm.Formatter.append(0x0, 0xc420457000, 0x28, 0x1000, 0xc427c07448, 0xc420368730, 0x0, 0x1, 0x0, 0x10, ...)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/orm/format.go:239 +0x762
github.com/go-pg/pg/orm.Formatter.Append(0x0, 0xc420457000, 0x28, 0x1000, 0x16e52aa, 0x42, 0xc420368730, 0x1, 0x1, 0xc4200c6cd0, ...)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/orm/format.go:158 +0x21f
github.com/go-pg/pg.(*DB).FormatQuery(0xc420342780, 0xc420457000, 0x28, 0x1000, 0x16e52aa, 0x42, 0xc420368730, 0x1, 0x1, 0x1f01b20, ...)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/db.go:411 +0x98
github.com/go-pg/pg/orm.(*Query).FormatQuery(0xc42798c180, 0xc420457000, 0x28, 0x1000, 0x16e52aa, 0x42, 0x0, 0x0, 0x0, 0xc420457000, ...)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/orm/query.go:803 +0xeb
github.com/go-pg/pg/orm.queryParamsAppender.AppendFormat(0x16e52aa, 0x42, 0x0, 0x0, 0x0, 0xc420457000, 0x28, 0x1000, 0x1740f00, 0xc42798c180, ...)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/orm/format.go:40 +0x9d
github.com/go-pg/pg/orm.(*Query).appendSet(0xc42798c180, 0xc420457000, 0x23, 0x1000, 0xc420039458, 0x23, 0x1a)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/orm/query.go:939 +0xbc
github.com/go-pg/pg/orm.updateQuery.mustAppendSet(0xc42798c180, 0xc420457000, 0xc420457000, 0x23, 0x1000, 0x23, 0x1000, 0x161fbe0, 0x1674da0, 0x1746ac0)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/orm/update.go:90 +0x415
github.com/go-pg/pg/orm.updateQuery.AppendQuery(0xc42798c180, 0xc42005e800, 0xc420457000, 0x5, 0x1000, 0x1010d03, 0x161fbe0, 0x1674da0, 0xc4200a9101, 0x1746ac0)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/orm/update.go:54 +0xda
github.com/go-pg/pg.appendQuery(0xc420457000, 0x5, 0x1000, 0x1740ee0, 0xc420342780, 0x1674da0, 0xc420368710, 0xc420368700, 0x1, 0x1, ...)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/messages.go:264 +0x24c
github.com/go-pg/pg.writeQueryMsg(0xc4201a8150, 0x1740ee0, 0xc420342780, 0x1674da0, 0xc420368710, 0xc420368700, 0x1, 0x1, 0x1d4136ae, 0x151ac6bae)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/messages.go:250 +0xdc
github.com/go-pg/pg.(*DB).simpleQueryData(0xc420342780, 0xc42045a000, 0x16a9740, 0xc4200d40a0, 0x1674da0, 0xc420368710, 0xc420368700, 0x1, 0x1, 0x1, ...)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/db.go:451 +0x8a
github.com/go-pg/pg.(*DB).Query(0xc420342780, 0x16a9740, 0xc4200d40a0, 0x1674da0, 0xc420368710, 0xc420368700, 0x1, 0x1, 0xc424378400, 0xc42005eb90, ...)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/db.go:246 +0x170
github.com/go-pg/pg/orm.(*Query).update(0xc42798c180, 0x0, 0x0, 0x0, 0xc420368600, 0x0, 0x1, 0xc42798c200, 0xc42022aea0)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/orm/query.go:698 +0x1e6
github.com/go-pg/pg/orm.(*Query).Update(0xc42798c180, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42798c180, 0xffffffffffffffff)
	/Users/Gadelkareem/go/src/github.com/go-pg/pg/orm/query.go:674 +0x4e

```

**Comment by gadelkareem** [comment]
Not sure if it a documentation bug but using `_data.` fixed it..
```
Db.Model(&books).Set("num = _data.num").Update()
```

**Comment by vmihailenco** [comment]
So far only following is supported: `db.Model(&books).Column("num").Update()`. I will see what can be done with your example.

**Comment by gadelkareem** [comment]
That example is from the wiki https://github.com/go-pg/pg/wiki/Writing-Queries#update I only had to changed `?title` to `_data.title` and it worked

**Comment by vmihailenco** [comment]
Right, but that example is for single update while you are using batch updates which are implemented differently.

**Comment by gadelkareem** [comment]
Actually it works! I guess that's an undiscovered feature then :) I even used a conditional clause inside Set.  
```
db.Model(& books).
 Column("col1", "col2", "col3").
 Set("col1 = _data.col1, col2 = _data.col2, col3 = _data.col3").
 Set("col4 = (CASE WHEN t.col1 = 0 AND t.col2 = 0 THEN col4 + 1 ELSE 0 END)").
 Set("col5 = (NOT t.col4>=? AND col5 = TRUE), col6 = (NOT t.col5>=? AND col6 = TRUE)", max, max).
 Update()
```
